language=es

data.path=data/
persons.file=data/persons.csv
products.file=data/products.csv
accounting.file=data/accounting.csv

person.name.min=2
person.name.max=50
person.lastname.min=2
person.lastname.max=50

product.price.max=999999.99
product.description.mode=UPPERCASE

list.page.size=5

csv.separator=,